# Copyright (c) 2020 Yoann MOUGNIBAS
# 
# This file is part of MusicWorkflow.
# 
# MusicWorkflow is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# MusicWorkflow is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with MusicWorkflow.  If not, see <https://www.gnu.org/licenses/>.

#
# Reference : https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#

# The name of the workflow
name: Main-CI

# Only build pull requests on "master" and "feature/*" target branch
on:
  pull_request:
    branches:
      - master
      - feature/*